call D:\Workspace\WSL\stop.bat
wscript.exe "D:\Workspace\Common\invisible.vbs" "D:\Workspace\ADB\start_adb_server.bat"
wscript.exe "D:\Workspace\Common\invisible.vbs" "D:\Workspace\Emulator\start_33_emulator.bat"
start /wait D:\AHK\AutoHotkey.exe "D:\Workspace\Emulator\wait_33_emulator.ahk"
wscript.exe "D:\Workspace\Common\invisible.vbs" "D:\Workspace\WSL\start_android_studio.bat"
wscript.exe "D:\Workspace\Common\invisible.vbs" "D:\Workspace\ADB\start_adb_client.bat"
start D:\AHK\AutoHotkey.exe "D:\Workspace\Emulator\toggle_android_studio_emulator_panels.ahk"
start /wait D:\AHK\AutoHotkey.exe "D:\Workspace\Emulator\hide_emulator_menus.ahk"
start /wait VirtualDesktop.exe "-Remove:Desktop_2"
start /wait VirtualDesktop.exe "-Remove:Desktop_3"
start /wait VirtualDesktop.exe "-Remove:Desktop_4"
start /wait D:\AHK\AutoHotkey.exe "D:\Workspace\Emulator\Single\setup_single_emulator_workspace.ahk"
start /wait D:\AHK\AutoHotkey.exe "D:\Workspace\Emulator\Single\setup_single_emulator.ahk"
start /wait VirtualDesktop.exe "-New" "-Name:Desktop_2" "-MoveWindowHandle:N^^otion - Home" "-MoveWindowHandle:O^bsidian" "-MoveWindow:Telegram" "-MoveWindowHandle:S^^lack"
start /wait VirtualDesktop.exe "-New" "-Name:Desktop_3" "-MoveWindowHandle:D^^iscord" "-MoveWindowHandle:M^^ultiMC" "-MoveWindowHandle:C^^hatterino" "-MoveWindowHandle:F^^ollowing - Twitch"
start /wait VirtualDesktop.exe "-New" "-Name:Desktop_4" "-MoveWindowHandle:A^^chieveToDo" "-MoveWindowHandle:F^^abric Wiki"